### PR TITLE
Feature/add task

### PR DESCRIPTION
**Pull request by avish-ds**
Added logic to generate task id using uuid.
Using uuid because if task id is generated using date and time has a possibility of generating same task id for two tasks.

### CODE REVIEW

**Review by shivamtech29 — COMMENTED** [review]
Revert commit deleted changes from srv/addBacklog.js.
Pls Add and Commit that file again for the same.

**Comment by avish-ds** [comment]
Added logic to create and add task id.
Task id is generated using uuid module.
Not using date and time because there is a possibility of two tasks having same task id.
Suggest any changes required.
image

**Review by shivamtech29 — APPROVED** [review]
Great Work. Appreciate your contribution.

**Comment by shivamtech29** [comment]
Will push this as patch update v0.1.2. Thanlks for the colaboration @avish-ds

**Pull request merged**
